The following is a more advanced python API version, which exactly matehes with c++, you should enable -DENABLE_PYBIND=ON before compile

In [1]:
import sys
#Assuming you have PyCandyxxx.so at ../../../
sys.path.append('../../../')
import torch
import PyCANDY as candy

Create an index by name tag (the same tags as in c++ cases), and then config it.

In [2]:
idxFlat=candy.createIndex('flat')
cfg={'vecDim':4,'metricType':"IP"}
idxFlat.setConfig(candy.dictToConfigMap(cfg))

True

In [3]:
a = torch.rand(4,4)
idxFlat.loadInitialTensor(a)
a2= torch.rand(4,4)
idxFlat.insertTensor(a2)
b=a[0:1]
ru=idxFlat.searchTensor(b,2)
print(ru)

[tensor([[0.2136, 0.8395, 0.7095, 0.9027],
        [0.4305, 0.3667, 0.8328, 0.7951]])]


Now, the idxFlat is the same as C++ class AbstractIndex, the APIs are totally the same as those in c++ cases!

This also works for dataloaders

In [7]:
dl=candy.createDataLoader('random')
cfg={'vecDim':4,'metricType':"IP",'vecVolume':10,'querySize':5}
dl.setConfig(candy.dictToConfigMap(cfg))
print(dl.getData())
print(dl.getQuery())


INFO:Thu May  9 11:39:01 2024:/home/tony/projects/CANDY/src/DataLoader/RandomDataLoader.cpp:28|virtual bool CANDY::RandomDataLoader::setConfig(INTELLI::ConfigMapPtr)|Generating [10x4], query size 5
tensor([[0.2558, 0.9050, 0.5109, 0.6242],
        [0.5704, 0.9277, 0.0232, 0.8905],
        [0.9258, 0.3159, 0.1076, 0.4448],
        [0.5312, 0.8756, 0.1155, 0.6262],
        [0.5665, 0.3706, 0.2453, 0.2599],
        [0.9563, 0.8296, 0.9201, 0.3850],
        [0.0536, 0.8374, 0.0130, 0.6243],
        [0.1989, 0.5926, 0.1954, 0.3914],
        [0.1690, 0.4334, 0.5606, 0.9281],
        [0.7406, 0.9541, 0.1273, 0.3315]])
tensor([[0.1989, 0.5926, 0.1954, 0.3914],
        [0.9563, 0.8296, 0.9201, 0.3850],
        [0.5704, 0.9277, 0.0232, 0.8905],
        [0.0536, 0.8374, 0.0130, 0.6243],
        [0.1690, 0.4334, 0.5606, 0.9281]])


We can also try to store other object along with tensors, for some AKNN

In [2]:
idxFlat=candy.createIndex('flatAMMIPObj')
cfg={'vecDim':4,'metricType':"IP"}
idxFlat.setConfig(candy.dictToConfigMap(cfg))

INFO:Mon Jul 22 19:55:37 2024:/home/tony/projects/CANDY/src/CANDY/FlatAMMIPObjIndex.cpp:24|virtual bool CANDY::FlatAMMIPObjIndex::setConfig(INTELLI::ConfigMapPtr)|Size of DCO=-1


True

In [6]:
a = torch.rand(4,4)
tr = [114514,7758258,666,999]
idxFlat.insertU64Object(a,tr)
b=a[0:1]
ru=idxFlat.searchU64Object(b,2)
print(ru)

[[114514, 999]]


We also provide in-file tensor interface, namely the RBT file

In [10]:
a = torch.rand(2,4)
candy.createRBT('example.rbt',a)
print(candy.getSizesFromRBT('example.rbt'))
b = torch.rand(2,4)
candy.appendTensorToRBT('example.rbt',b)
print(candy.getSizesFromRBT('example.rbt'))
print(a)
print(b)
print('here is what is read form rbt')
print(candy.readRowsFromRBT('example.rbt',1,3))

[2, 4]
[4, 4]
tensor([[0.3140, 0.4143, 0.4821, 0.6868],
        [0.3231, 0.3626, 0.4190, 0.7713]])
tensor([[0.0984, 0.6540, 0.0948, 0.5400],
        [0.2832, 0.5526, 0.0377, 0.5075]])
here is what is read form rbt
tensor([[0.3231, 0.3626, 0.4190, 0.7713],
        [0.0984, 0.6540, 0.0948, 0.5400]])
